/*
    ICTPRG532 AT2 - Math Quiz Application
    File name:  MathQuiz_Student.java
    Author:     Benjamin Cotterill
    Version:    1.0
    Notes:      Includes quiz answer panel for student and client components of client/server network.
 */

package mathquiz;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.net.SocketException;
import javax.swing.JOptionPane;

public class MathQuiz_Student extends javax.swing.JFrame {
    static Socket socket;
    static DataInputStream dataInputStream;
    static DataOutputStream dataOutputStream;
    static int correctAnswer;
    int studentAnswer;

    /**
     * Creates new form MathQuiz_Student
     */
    public MathQuiz_Student() {
        initComponents();
        submit_JButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        core_JPanel = new javax.swing.JPanel();
        student_JPanel = new javax.swing.JPanel();
        student_JLabel = new javax.swing.JLabel();
        input_JPanel = new javax.swing.JPanel();
        inputGuide_JPanel = new javax.swing.JPanel();
        inputGuide_JLabel = new javax.swing.JLabel();
        question_JLabel = new javax.swing.JLabel();
        question_JTextField = new javax.swing.JTextField();
        answer_JLabel = new javax.swing.JLabel();
        answer_JTextField = new javax.swing.JTextField();
        submit_JButton = new javax.swing.JButton();
        exit_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        core_JPanel.setBackground(new java.awt.Color(255, 250, 240));

        student_JPanel.setBackground(new java.awt.Color(0, 0, 200));
        student_JPanel.setPreferredSize(new java.awt.Dimension(400, 30));

        student_JLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        student_JLabel.setForeground(new java.awt.Color(255, 255, 255));
        student_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        student_JLabel.setText("Student");

        javax.swing.GroupLayout student_JPanelLayout = new javax.swing.GroupLayout(student_JPanel);
        student_JPanel.setLayout(student_JPanelLayout);
        student_JPanelLayout.setHorizontalGroup(
            student_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        student_JPanelLayout.setVerticalGroup(
            student_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        input_JPanel.setBackground(new java.awt.Color(214, 217, 223));
        input_JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inputGuide_JPanel.setBackground(new java.awt.Color(0, 0, 200));

        inputGuide_JLabel.setForeground(new java.awt.Color(255, 255, 255));
        inputGuide_JLabel.setText("Enter your answer and click Submit");

        javax.swing.GroupLayout inputGuide_JPanelLayout = new javax.swing.GroupLayout(inputGuide_JPanel);
        inputGuide_JPanel.setLayout(inputGuide_JPanelLayout);
        inputGuide_JPanelLayout.setHorizontalGroup(
            inputGuide_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputGuide_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputGuide_JLabel)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        inputGuide_JPanelLayout.setVerticalGroup(
            inputGuide_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputGuide_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputGuide_JLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        question_JLabel.setText("Question:");

        question_JTextField.setEditable(false);

        answer_JLabel.setText("Your Answer:");

        submit_JButton.setText("Submit");
        submit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout input_JPanelLayout = new javax.swing.GroupLayout(input_JPanel);
        input_JPanel.setLayout(input_JPanelLayout);
        input_JPanelLayout.setHorizontalGroup(
            input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputGuide_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(input_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit_JButton))
                    .addGroup(input_JPanelLayout.createSequentialGroup()
                        .addGroup(input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question_JLabel)
                            .addComponent(answer_JLabel))
                        .addGap(18, 18, 18)
                        .addGroup(input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer_JTextField)
                            .addComponent(question_JTextField))))
                .addContainerGap())
        );

        input_JPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {answer_JLabel, question_JLabel});

        input_JPanelLayout.setVerticalGroup(
            input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_JPanelLayout.createSequentialGroup()
                .addComponent(inputGuide_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question_JLabel))
                .addGap(18, 18, 18)
                .addGroup(input_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(submit_JButton)
                .addContainerGap())
        );

        exit_JButton.setText("Exit");
        exit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout core_JPanelLayout = new javax.swing.GroupLayout(core_JPanel);
        core_JPanel.setLayout(core_JPanelLayout);
        core_JPanelLayout.setHorizontalGroup(
            core_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(core_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(core_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, core_JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit_JButton)))
                .addContainerGap())
        );
        core_JPanelLayout.setVerticalGroup(
            core_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(core_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(exit_JButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(core_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(core_JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Checks if student has input an answer. Calls checkAnswer to ensure that answer is correct. Sends answer to server.
     * @param evt 
     */
    private void submit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_JButtonActionPerformed
        studentAnswer = -9999;
        try {
            studentAnswer = Integer.parseInt(answer_JTextField.getText());
        } catch(NumberFormatException e) { // Notify student that their answer must be a number.
            String exceptionStr = "You must enter a numeric answer to the math question";
            JOptionPane.showMessageDialog(null, exceptionStr, "ERROR IN ANSWER", JOptionPane.ERROR_MESSAGE);
        }
        String messageOut = checkAnswer(studentAnswer, correctAnswer); // Call checkAnswer method to check the student's answer.
        question_JTextField.setText("");
        answer_JTextField.setText("");
        
        try {
            dataOutputStream.writeUTF(messageOut); // Send answer to server.
            submit_JButton.setEnabled(false);
        } catch(IOException e) { // Catches error if server does not confirm receipt.
            String exceptionStr = "Client Send Error : " + e.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr, "CLIENT SEND ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submit_JButtonActionPerformed

    /**
     * Hides the window, returns allocated resources back to OS and closes the program with an exit code of 0. Intentionally causes SocketException for server client.
     * @param evt 
     */
    private void exit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_JButtonActionPerformed
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exit_JButtonActionPerformed

    /**
     * Checks if the student answered correctly. String of "y" if teacher answer and student answer match and String of "n" if they do not.
     * @param studentAnswer
     * @param correctAnswer
     * @return 
     */
    private static String checkAnswer(int studentAnswer, int correctAnswer) {
        String messageOut = "n";
        if(studentAnswer == correctAnswer) {
            JOptionPane.showMessageDialog(null, "Correct!", "Correct", JOptionPane.PLAIN_MESSAGE);
            messageOut = "y";
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, not correct!", "NOT Correct", JOptionPane.PLAIN_MESSAGE);
        }
        return messageOut;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathQuiz_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MathQuiz_Student().setVisible(true);
        });
        
        try {
            socket = new Socket("127.0.0.1", 1201); // Create new TCP/IP socket and handshake with server.
            dataInputStream = new DataInputStream(socket.getInputStream()); // Create input stream for socket.
            dataOutputStream = new DataOutputStream(socket.getOutputStream()); // Create output stream for socket.
            String messageIn = "";
            while(!messageIn.equals("exit")) {
                messageIn = dataInputStream.readUTF(); // Read incoming messages expected to be in UTF format.
                submit_JButton.setEnabled(true);
                String[] arrayMathQuestions = messageIn.split(" "); // Split message into segments to prevent answer being displayed.
                int number1 = Integer.parseInt(arrayMathQuestions[0]);
                String operator = arrayMathQuestions[1];
                int number2 = Integer.parseInt(arrayMathQuestions[2]);
                correctAnswer = Integer.parseInt(arrayMathQuestions[4]);
                question_JTextField.setText(number1 + " " + operator + " " + number2 + " =");
            }
        } catch(SocketException se) {
            String exceptionStr = "Client Socket Error: " + se.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr, "CLIENT ERROR", JOptionPane.ERROR_MESSAGE);
        } catch(IOException e) {
            String exceptionStr = "Client Error: " + e.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr, "CLIENT ERROR", JOptionPane.ERROR_MESSAGE);
        } catch(NumberFormatException e) {
            String exceptionStr = "Numeric Error: " + e.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr, "NUMERIC ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer_JLabel;
    private javax.swing.JTextField answer_JTextField;
    private javax.swing.JPanel core_JPanel;
    private javax.swing.JButton exit_JButton;
    private javax.swing.JLabel inputGuide_JLabel;
    private javax.swing.JPanel inputGuide_JPanel;
    private javax.swing.JPanel input_JPanel;
    private javax.swing.JLabel question_JLabel;
    private static javax.swing.JTextField question_JTextField;
    private javax.swing.JLabel student_JLabel;
    private javax.swing.JPanel student_JPanel;
    private static javax.swing.JButton submit_JButton;
    // End of variables declaration//GEN-END:variables
}
